package stitching

import (
	"image"
	"math"
	"math/rand"
	"testing"

	cv "github.com/malcolmston/opencv"
)

// rotY returns a rotation of theta radians about the Y axis.
func rotY(theta float64) mat3 {
	c, s := math.Cos(theta), math.Sin(theta)
	return mat3{c, 0, s, 0, 1, 0, -s, 0, c}
}

// syntheticCameras builds a deterministic rotational-camera rig: several cameras
// sharing focal fTrue and principal point (w/2, h/2), yawed about the Y axis by
// the given angles. It also returns pairwise correspondences between consecutive
// cameras, generated by projecting shared 3-D directions into both views (points
// that fall inside both images are kept).
func syntheticCameras(fTrue float64, w, h int, angles []float64, seed int64) (cams []CameraParams, sizes []image.Point, matches []MatchesInfo) {
	n := len(angles)
	cams = make([]CameraParams, n)
	sizes = make([]image.Point, n)
	rots := make([]mat3, n)
	for i, a := range angles {
		rots[i] = rotY(a)
		cams[i] = CameraParams{Focal: fTrue, Aspect: 1, PPX: float64(w) / 2, PPY: float64(h) / 2, R: [9]float64(rots[i])}
		sizes[i] = image.Point{X: w, Y: h}
	}
	project := func(i int, dir [3]float64) (float64, float64, bool) {
		cx, cy, cz := rots[i].vec(dir[0], dir[1], dir[2])
		if cz <= 1e-3 {
			return 0, 0, false
		}
		px := fTrue*cx/cz + float64(w)/2
		py := fTrue*cy/cz + float64(h)/2
		if px < 0 || px >= float64(w) || py < 0 || py >= float64(h) {
			return 0, 0, false
		}
		return px, py, true
	}
	rng := rand.New(rand.NewSource(seed))
	for i := 0; i+1 < n; i++ {
		var mi MatchesInfo
		mi.Src = i
		mi.Dst = i + 1
		for len(mi.SrcPoints) < 60 {
			dir := [3]float64{
				(rng.Float64()*2 - 1) * 0.5,
				(rng.Float64()*2 - 1) * 0.35,
				1,
			}
			nrm := math.Sqrt(dir[0]*dir[0] + dir[1]*dir[1] + dir[2]*dir[2])
			dir = [3]float64{dir[0] / nrm, dir[1] / nrm, dir[2] / nrm}
			sx, sy, ok1 := project(i, dir)
			dx, dy, ok2 := project(i+1, dir)
			if !ok1 || !ok2 {
				continue
			}
			mi.SrcPoints = append(mi.SrcPoints, image.Point{X: int(math.Round(sx)), Y: int(math.Round(sy))})
			mi.DstPoints = append(mi.DstPoints, image.Point{X: int(math.Round(dx)), Y: int(math.Round(dy))})
		}
		matches = append(matches, mi)
	}
	return cams, sizes, matches
}

func TestEstimateFocalsFromHomography(t *testing.T) {
	fTrue := 300.0
	w, h := 400, 300
	// Homography between two views of the same rotating camera: H = K R K⁻¹.
	k := mat3{fTrue, 0, float64(w) / 2, 0, fTrue, float64(h) / 2, 0, 0, 1}
	kInv, _ := k.inv3()
	h1 := k.mul(rotY(0.3)).mul(kInv)
	// Normalise so h8 = 1.
	for i := range h1 {
		h1[i] /= h1[8]
	}
	f0, f1, ok0, ok1 := EstimateFocalsFromHomography(cv.PerspectiveMatrix(h1))
	if !ok0 || !ok1 {
		t.Fatalf("focal estimation failed: ok0=%v ok1=%v", ok0, ok1)
	}
	// The robust estimate (used by the estimator) is the geometric mean of the two
	// per-camera focals; it recovers the true focal closely.
	geo := math.Sqrt(f0 * f1)
	if math.Abs(geo-fTrue)/fTrue > 0.1 {
		t.Errorf("estimated focal (geo mean) = %.2f, want %.2f ± 10%%", geo, fTrue)
	}
}

func TestHomographyBasedEstimator(t *testing.T) {
	fTrue := 260.0
	w, h := 320, 240
	angles := []float64{-0.25, 0, 0.25}
	trueCams, sizes, matches := syntheticCameras(fTrue, w, h, angles, 7)

	est := HomographyBasedEstimator{}
	cams, ok := est.Estimate(sizes, matches)
	if !ok {
		t.Fatal("estimator returned not-ok")
	}
	if len(cams) != len(angles) {
		t.Fatalf("got %d cameras, want %d", len(cams), len(angles))
	}
	// Focal recovered within 8%.
	if rel := math.Abs(cams[0].Focal-fTrue) / fTrue; rel > 0.08 {
		t.Errorf("estimated focal = %.2f, want %.2f (%.1f%% off)", cams[0].Focal, fTrue, rel*100)
	}
	// Rotations must be proper (orthonormal, det ≈ 1).
	for i, c := range cams {
		if d := c.rot().det(); math.Abs(d-1) > 1e-3 {
			t.Errorf("camera %d rotation det = %.5f, want 1", i, d)
		}
	}
	// The estimator fixes camera 0 to identity, so its recovered relative rotation
	// to camera 1 should match the true relative rotation R1·R0ᵀ.
	relTrue := mat3(trueCams[1].R).mul(mat3(trueCams[0].R).transpose())
	relEst := cams[1].rot()
	var maxDiff float64
	for i := range relTrue {
		maxDiff = math.Max(maxDiff, math.Abs(relTrue[i]-relEst[i]))
	}
	if maxDiff > 0.08 {
		t.Errorf("relative rotation error = %.4f, want <= 0.08", maxDiff)
	}
}
