// Code generated by core value-type builder. DO NOT EDIT by hand.

package core

import (
	"fmt"
)

// Matx12f is a 1x2 matrix of float32 stored row-major, mirroring cv::Matx12f.
type Matx12f [2]float32

// NewMatx12f builds a Matx12f from 2 row-major elements.
func NewMatx12f(e0 float32, e1 float32) Matx12f { return Matx12f{e0, e1} }

// At returns the element at row i, column j (0-indexed).
func (m Matx12f) At(i, j int) float32 { return m[i*2+j] }

// Rows returns the row count (1).
func (m Matx12f) Rows() int { return 1 }

// Cols returns the column count (2).
func (m Matx12f) Cols() int { return 2 }

// Add returns the element-wise sum m+o.
func (m Matx12f) Add(o Matx12f) Matx12f {
	var r Matx12f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx12f) Sub(o Matx12f) Matx12f {
	var r Matx12f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx12f) Scale(s float32) Matx12f {
	var r Matx12f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 2x1 transpose as a Matx21f.
func (m Matx12f) Transpose() Matx21f {
	var t Matx21f
	for i := 0; i < 1; i++ {
		for j := 0; j < 2; j++ {
			t[j*1+i] = m[i*2+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx12f) String() string { return fmt.Sprintf("%v", [2]float32(m)) }

// Matx12d is a 1x2 matrix of float64 stored row-major, mirroring cv::Matx12d.
type Matx12d [2]float64

// NewMatx12d builds a Matx12d from 2 row-major elements.
func NewMatx12d(e0 float64, e1 float64) Matx12d { return Matx12d{e0, e1} }

// At returns the element at row i, column j (0-indexed).
func (m Matx12d) At(i, j int) float64 { return m[i*2+j] }

// Rows returns the row count (1).
func (m Matx12d) Rows() int { return 1 }

// Cols returns the column count (2).
func (m Matx12d) Cols() int { return 2 }

// Add returns the element-wise sum m+o.
func (m Matx12d) Add(o Matx12d) Matx12d {
	var r Matx12d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx12d) Sub(o Matx12d) Matx12d {
	var r Matx12d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx12d) Scale(s float64) Matx12d {
	var r Matx12d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 2x1 transpose as a Matx21d.
func (m Matx12d) Transpose() Matx21d {
	var t Matx21d
	for i := 0; i < 1; i++ {
		for j := 0; j < 2; j++ {
			t[j*1+i] = m[i*2+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx12d) String() string { return fmt.Sprintf("%v", [2]float64(m)) }

// Matx13f is a 1x3 matrix of float32 stored row-major, mirroring cv::Matx13f.
type Matx13f [3]float32

// NewMatx13f builds a Matx13f from 3 row-major elements.
func NewMatx13f(e0 float32, e1 float32, e2 float32) Matx13f { return Matx13f{e0, e1, e2} }

// At returns the element at row i, column j (0-indexed).
func (m Matx13f) At(i, j int) float32 { return m[i*3+j] }

// Rows returns the row count (1).
func (m Matx13f) Rows() int { return 1 }

// Cols returns the column count (3).
func (m Matx13f) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx13f) Add(o Matx13f) Matx13f {
	var r Matx13f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx13f) Sub(o Matx13f) Matx13f {
	var r Matx13f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx13f) Scale(s float32) Matx13f {
	var r Matx13f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x1 transpose as a Matx31f.
func (m Matx13f) Transpose() Matx31f {
	var t Matx31f
	for i := 0; i < 1; i++ {
		for j := 0; j < 3; j++ {
			t[j*1+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx13f) String() string { return fmt.Sprintf("%v", [3]float32(m)) }

// Matx13d is a 1x3 matrix of float64 stored row-major, mirroring cv::Matx13d.
type Matx13d [3]float64

// NewMatx13d builds a Matx13d from 3 row-major elements.
func NewMatx13d(e0 float64, e1 float64, e2 float64) Matx13d { return Matx13d{e0, e1, e2} }

// At returns the element at row i, column j (0-indexed).
func (m Matx13d) At(i, j int) float64 { return m[i*3+j] }

// Rows returns the row count (1).
func (m Matx13d) Rows() int { return 1 }

// Cols returns the column count (3).
func (m Matx13d) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx13d) Add(o Matx13d) Matx13d {
	var r Matx13d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx13d) Sub(o Matx13d) Matx13d {
	var r Matx13d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx13d) Scale(s float64) Matx13d {
	var r Matx13d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x1 transpose as a Matx31d.
func (m Matx13d) Transpose() Matx31d {
	var t Matx31d
	for i := 0; i < 1; i++ {
		for j := 0; j < 3; j++ {
			t[j*1+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx13d) String() string { return fmt.Sprintf("%v", [3]float64(m)) }

// Matx14f is a 1x4 matrix of float32 stored row-major, mirroring cv::Matx14f.
type Matx14f [4]float32

// NewMatx14f builds a Matx14f from 4 row-major elements.
func NewMatx14f(e0 float32, e1 float32, e2 float32, e3 float32) Matx14f {
	return Matx14f{e0, e1, e2, e3}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx14f) At(i, j int) float32 { return m[i*4+j] }

// Rows returns the row count (1).
func (m Matx14f) Rows() int { return 1 }

// Cols returns the column count (4).
func (m Matx14f) Cols() int { return 4 }

// Add returns the element-wise sum m+o.
func (m Matx14f) Add(o Matx14f) Matx14f {
	var r Matx14f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx14f) Sub(o Matx14f) Matx14f {
	var r Matx14f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx14f) Scale(s float32) Matx14f {
	var r Matx14f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 4x1 transpose as a Matx41f.
func (m Matx14f) Transpose() Matx41f {
	var t Matx41f
	for i := 0; i < 1; i++ {
		for j := 0; j < 4; j++ {
			t[j*1+i] = m[i*4+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx14f) String() string { return fmt.Sprintf("%v", [4]float32(m)) }

// Matx14d is a 1x4 matrix of float64 stored row-major, mirroring cv::Matx14d.
type Matx14d [4]float64

// NewMatx14d builds a Matx14d from 4 row-major elements.
func NewMatx14d(e0 float64, e1 float64, e2 float64, e3 float64) Matx14d {
	return Matx14d{e0, e1, e2, e3}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx14d) At(i, j int) float64 { return m[i*4+j] }

// Rows returns the row count (1).
func (m Matx14d) Rows() int { return 1 }

// Cols returns the column count (4).
func (m Matx14d) Cols() int { return 4 }

// Add returns the element-wise sum m+o.
func (m Matx14d) Add(o Matx14d) Matx14d {
	var r Matx14d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx14d) Sub(o Matx14d) Matx14d {
	var r Matx14d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx14d) Scale(s float64) Matx14d {
	var r Matx14d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 4x1 transpose as a Matx41d.
func (m Matx14d) Transpose() Matx41d {
	var t Matx41d
	for i := 0; i < 1; i++ {
		for j := 0; j < 4; j++ {
			t[j*1+i] = m[i*4+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx14d) String() string { return fmt.Sprintf("%v", [4]float64(m)) }

// Matx16f is a 1x6 matrix of float32 stored row-major, mirroring cv::Matx16f.
type Matx16f [6]float32

// NewMatx16f builds a Matx16f from 6 row-major elements.
func NewMatx16f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32) Matx16f {
	return Matx16f{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx16f) At(i, j int) float32 { return m[i*6+j] }

// Rows returns the row count (1).
func (m Matx16f) Rows() int { return 1 }

// Cols returns the column count (6).
func (m Matx16f) Cols() int { return 6 }

// Add returns the element-wise sum m+o.
func (m Matx16f) Add(o Matx16f) Matx16f {
	var r Matx16f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx16f) Sub(o Matx16f) Matx16f {
	var r Matx16f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx16f) Scale(s float32) Matx16f {
	var r Matx16f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 6x1 transpose as a Matx61f.
func (m Matx16f) Transpose() Matx61f {
	var t Matx61f
	for i := 0; i < 1; i++ {
		for j := 0; j < 6; j++ {
			t[j*1+i] = m[i*6+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx16f) String() string { return fmt.Sprintf("%v", [6]float32(m)) }

// Matx16d is a 1x6 matrix of float64 stored row-major, mirroring cv::Matx16d.
type Matx16d [6]float64

// NewMatx16d builds a Matx16d from 6 row-major elements.
func NewMatx16d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64) Matx16d {
	return Matx16d{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx16d) At(i, j int) float64 { return m[i*6+j] }

// Rows returns the row count (1).
func (m Matx16d) Rows() int { return 1 }

// Cols returns the column count (6).
func (m Matx16d) Cols() int { return 6 }

// Add returns the element-wise sum m+o.
func (m Matx16d) Add(o Matx16d) Matx16d {
	var r Matx16d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx16d) Sub(o Matx16d) Matx16d {
	var r Matx16d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx16d) Scale(s float64) Matx16d {
	var r Matx16d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 6x1 transpose as a Matx61d.
func (m Matx16d) Transpose() Matx61d {
	var t Matx61d
	for i := 0; i < 1; i++ {
		for j := 0; j < 6; j++ {
			t[j*1+i] = m[i*6+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx16d) String() string { return fmt.Sprintf("%v", [6]float64(m)) }

// Matx21f is a 2x1 matrix of float32 stored row-major, mirroring cv::Matx21f.
type Matx21f [2]float32

// NewMatx21f builds a Matx21f from 2 row-major elements.
func NewMatx21f(e0 float32, e1 float32) Matx21f { return Matx21f{e0, e1} }

// At returns the element at row i, column j (0-indexed).
func (m Matx21f) At(i, j int) float32 { return m[i*1+j] }

// Rows returns the row count (2).
func (m Matx21f) Rows() int { return 2 }

// Cols returns the column count (1).
func (m Matx21f) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx21f) Add(o Matx21f) Matx21f {
	var r Matx21f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx21f) Sub(o Matx21f) Matx21f {
	var r Matx21f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx21f) Scale(s float32) Matx21f {
	var r Matx21f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x2 transpose as a Matx12f.
func (m Matx21f) Transpose() Matx12f {
	var t Matx12f
	for i := 0; i < 2; i++ {
		for j := 0; j < 1; j++ {
			t[j*2+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx21f) String() string { return fmt.Sprintf("%v", [2]float32(m)) }

// Matx21d is a 2x1 matrix of float64 stored row-major, mirroring cv::Matx21d.
type Matx21d [2]float64

// NewMatx21d builds a Matx21d from 2 row-major elements.
func NewMatx21d(e0 float64, e1 float64) Matx21d { return Matx21d{e0, e1} }

// At returns the element at row i, column j (0-indexed).
func (m Matx21d) At(i, j int) float64 { return m[i*1+j] }

// Rows returns the row count (2).
func (m Matx21d) Rows() int { return 2 }

// Cols returns the column count (1).
func (m Matx21d) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx21d) Add(o Matx21d) Matx21d {
	var r Matx21d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx21d) Sub(o Matx21d) Matx21d {
	var r Matx21d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx21d) Scale(s float64) Matx21d {
	var r Matx21d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x2 transpose as a Matx12d.
func (m Matx21d) Transpose() Matx12d {
	var t Matx12d
	for i := 0; i < 2; i++ {
		for j := 0; j < 1; j++ {
			t[j*2+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx21d) String() string { return fmt.Sprintf("%v", [2]float64(m)) }

// Matx31f is a 3x1 matrix of float32 stored row-major, mirroring cv::Matx31f.
type Matx31f [3]float32

// NewMatx31f builds a Matx31f from 3 row-major elements.
func NewMatx31f(e0 float32, e1 float32, e2 float32) Matx31f { return Matx31f{e0, e1, e2} }

// At returns the element at row i, column j (0-indexed).
func (m Matx31f) At(i, j int) float32 { return m[i*1+j] }

// Rows returns the row count (3).
func (m Matx31f) Rows() int { return 3 }

// Cols returns the column count (1).
func (m Matx31f) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx31f) Add(o Matx31f) Matx31f {
	var r Matx31f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx31f) Sub(o Matx31f) Matx31f {
	var r Matx31f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx31f) Scale(s float32) Matx31f {
	var r Matx31f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x3 transpose as a Matx13f.
func (m Matx31f) Transpose() Matx13f {
	var t Matx13f
	for i := 0; i < 3; i++ {
		for j := 0; j < 1; j++ {
			t[j*3+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx31f) String() string { return fmt.Sprintf("%v", [3]float32(m)) }

// Matx31d is a 3x1 matrix of float64 stored row-major, mirroring cv::Matx31d.
type Matx31d [3]float64

// NewMatx31d builds a Matx31d from 3 row-major elements.
func NewMatx31d(e0 float64, e1 float64, e2 float64) Matx31d { return Matx31d{e0, e1, e2} }

// At returns the element at row i, column j (0-indexed).
func (m Matx31d) At(i, j int) float64 { return m[i*1+j] }

// Rows returns the row count (3).
func (m Matx31d) Rows() int { return 3 }

// Cols returns the column count (1).
func (m Matx31d) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx31d) Add(o Matx31d) Matx31d {
	var r Matx31d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx31d) Sub(o Matx31d) Matx31d {
	var r Matx31d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx31d) Scale(s float64) Matx31d {
	var r Matx31d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x3 transpose as a Matx13d.
func (m Matx31d) Transpose() Matx13d {
	var t Matx13d
	for i := 0; i < 3; i++ {
		for j := 0; j < 1; j++ {
			t[j*3+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx31d) String() string { return fmt.Sprintf("%v", [3]float64(m)) }

// Matx41f is a 4x1 matrix of float32 stored row-major, mirroring cv::Matx41f.
type Matx41f [4]float32

// NewMatx41f builds a Matx41f from 4 row-major elements.
func NewMatx41f(e0 float32, e1 float32, e2 float32, e3 float32) Matx41f {
	return Matx41f{e0, e1, e2, e3}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx41f) At(i, j int) float32 { return m[i*1+j] }

// Rows returns the row count (4).
func (m Matx41f) Rows() int { return 4 }

// Cols returns the column count (1).
func (m Matx41f) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx41f) Add(o Matx41f) Matx41f {
	var r Matx41f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx41f) Sub(o Matx41f) Matx41f {
	var r Matx41f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx41f) Scale(s float32) Matx41f {
	var r Matx41f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x4 transpose as a Matx14f.
func (m Matx41f) Transpose() Matx14f {
	var t Matx14f
	for i := 0; i < 4; i++ {
		for j := 0; j < 1; j++ {
			t[j*4+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx41f) String() string { return fmt.Sprintf("%v", [4]float32(m)) }

// Matx41d is a 4x1 matrix of float64 stored row-major, mirroring cv::Matx41d.
type Matx41d [4]float64

// NewMatx41d builds a Matx41d from 4 row-major elements.
func NewMatx41d(e0 float64, e1 float64, e2 float64, e3 float64) Matx41d {
	return Matx41d{e0, e1, e2, e3}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx41d) At(i, j int) float64 { return m[i*1+j] }

// Rows returns the row count (4).
func (m Matx41d) Rows() int { return 4 }

// Cols returns the column count (1).
func (m Matx41d) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx41d) Add(o Matx41d) Matx41d {
	var r Matx41d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx41d) Sub(o Matx41d) Matx41d {
	var r Matx41d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx41d) Scale(s float64) Matx41d {
	var r Matx41d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x4 transpose as a Matx14d.
func (m Matx41d) Transpose() Matx14d {
	var t Matx14d
	for i := 0; i < 4; i++ {
		for j := 0; j < 1; j++ {
			t[j*4+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx41d) String() string { return fmt.Sprintf("%v", [4]float64(m)) }

// Matx61f is a 6x1 matrix of float32 stored row-major, mirroring cv::Matx61f.
type Matx61f [6]float32

// NewMatx61f builds a Matx61f from 6 row-major elements.
func NewMatx61f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32) Matx61f {
	return Matx61f{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx61f) At(i, j int) float32 { return m[i*1+j] }

// Rows returns the row count (6).
func (m Matx61f) Rows() int { return 6 }

// Cols returns the column count (1).
func (m Matx61f) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx61f) Add(o Matx61f) Matx61f {
	var r Matx61f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx61f) Sub(o Matx61f) Matx61f {
	var r Matx61f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx61f) Scale(s float32) Matx61f {
	var r Matx61f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x6 transpose as a Matx16f.
func (m Matx61f) Transpose() Matx16f {
	var t Matx16f
	for i := 0; i < 6; i++ {
		for j := 0; j < 1; j++ {
			t[j*6+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx61f) String() string { return fmt.Sprintf("%v", [6]float32(m)) }

// Matx61d is a 6x1 matrix of float64 stored row-major, mirroring cv::Matx61d.
type Matx61d [6]float64

// NewMatx61d builds a Matx61d from 6 row-major elements.
func NewMatx61d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64) Matx61d {
	return Matx61d{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx61d) At(i, j int) float64 { return m[i*1+j] }

// Rows returns the row count (6).
func (m Matx61d) Rows() int { return 6 }

// Cols returns the column count (1).
func (m Matx61d) Cols() int { return 1 }

// Add returns the element-wise sum m+o.
func (m Matx61d) Add(o Matx61d) Matx61d {
	var r Matx61d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx61d) Sub(o Matx61d) Matx61d {
	var r Matx61d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx61d) Scale(s float64) Matx61d {
	var r Matx61d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 1x6 transpose as a Matx16d.
func (m Matx61d) Transpose() Matx16d {
	var t Matx16d
	for i := 0; i < 6; i++ {
		for j := 0; j < 1; j++ {
			t[j*6+i] = m[i*1+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx61d) String() string { return fmt.Sprintf("%v", [6]float64(m)) }

// Matx22f is a 2x2 matrix of float32 stored row-major, mirroring cv::Matx22f.
type Matx22f [4]float32

// NewMatx22f builds a Matx22f from 4 row-major elements.
func NewMatx22f(e0 float32, e1 float32, e2 float32, e3 float32) Matx22f {
	return Matx22f{e0, e1, e2, e3}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx22f) At(i, j int) float32 { return m[i*2+j] }

// Rows returns the row count (2).
func (m Matx22f) Rows() int { return 2 }

// Cols returns the column count (2).
func (m Matx22f) Cols() int { return 2 }

// Add returns the element-wise sum m+o.
func (m Matx22f) Add(o Matx22f) Matx22f {
	var r Matx22f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx22f) Sub(o Matx22f) Matx22f {
	var r Matx22f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx22f) Scale(s float32) Matx22f {
	var r Matx22f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 2x2 transpose as a Matx22f.
func (m Matx22f) Transpose() Matx22f {
	var t Matx22f
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			t[j*2+i] = m[i*2+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx22f) String() string { return fmt.Sprintf("%v", [4]float32(m)) }

// Mul returns the matrix product m*o.
func (m Matx22f) Mul(o Matx22f) Matx22f {
	var r Matx22f
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			var s float32
			for k := 0; k < 2; k++ {
				s += m[i*2+k] * o[k*2+j]
			}
			r[i*2+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx22f) MulVec(v Vec2f) Vec2f {
	var r Vec2f
	for i := 0; i < 2; i++ {
		var s float32
		for k := 0; k < 2; k++ {
			s += m[i*2+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx22f) Trace() float64 {
	var s float64
	for i := 0; i < 2; i++ {
		s += float64(m[i*2+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx22f) Determinant() float64 {
	var a [2][2]float64
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			a[i][j] = float64(m[i*2+j])
		}
	}
	det := 1.0
	for col := 0; col < 2; col++ {
		p := col
		for rr := col + 1; rr < 2; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 2; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 2; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx22f) Inverse() (Matx22f, bool) {
	var a [2][4]float64
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			a[i][j] = float64(m[i*2+j])
		}
		a[i][2+i] = 1
	}
	for col := 0; col < 2; col++ {
		p := col
		for rr := col + 1; rr < 2; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx22f
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 4; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 2; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 4; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx22f
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			r[i*2+j] = float32(a[i][2+j])
		}
	}
	return r, true
}

// Matx22fIdentity returns the 2x2 identity matrix.
func Matx22fIdentity() Matx22f {
	var r Matx22f
	for i := 0; i < 2; i++ {
		r[i*2+i] = 1
	}
	return r
}

// Matx22d is a 2x2 matrix of float64 stored row-major, mirroring cv::Matx22d.
type Matx22d [4]float64

// NewMatx22d builds a Matx22d from 4 row-major elements.
func NewMatx22d(e0 float64, e1 float64, e2 float64, e3 float64) Matx22d {
	return Matx22d{e0, e1, e2, e3}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx22d) At(i, j int) float64 { return m[i*2+j] }

// Rows returns the row count (2).
func (m Matx22d) Rows() int { return 2 }

// Cols returns the column count (2).
func (m Matx22d) Cols() int { return 2 }

// Add returns the element-wise sum m+o.
func (m Matx22d) Add(o Matx22d) Matx22d {
	var r Matx22d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx22d) Sub(o Matx22d) Matx22d {
	var r Matx22d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx22d) Scale(s float64) Matx22d {
	var r Matx22d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 2x2 transpose as a Matx22d.
func (m Matx22d) Transpose() Matx22d {
	var t Matx22d
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			t[j*2+i] = m[i*2+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx22d) String() string { return fmt.Sprintf("%v", [4]float64(m)) }

// Mul returns the matrix product m*o.
func (m Matx22d) Mul(o Matx22d) Matx22d {
	var r Matx22d
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			var s float64
			for k := 0; k < 2; k++ {
				s += m[i*2+k] * o[k*2+j]
			}
			r[i*2+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx22d) MulVec(v Vec2d) Vec2d {
	var r Vec2d
	for i := 0; i < 2; i++ {
		var s float64
		for k := 0; k < 2; k++ {
			s += m[i*2+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx22d) Trace() float64 {
	var s float64
	for i := 0; i < 2; i++ {
		s += float64(m[i*2+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx22d) Determinant() float64 {
	var a [2][2]float64
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			a[i][j] = float64(m[i*2+j])
		}
	}
	det := 1.0
	for col := 0; col < 2; col++ {
		p := col
		for rr := col + 1; rr < 2; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 2; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 2; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx22d) Inverse() (Matx22d, bool) {
	var a [2][4]float64
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			a[i][j] = float64(m[i*2+j])
		}
		a[i][2+i] = 1
	}
	for col := 0; col < 2; col++ {
		p := col
		for rr := col + 1; rr < 2; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx22d
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 4; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 2; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 4; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx22d
	for i := 0; i < 2; i++ {
		for j := 0; j < 2; j++ {
			r[i*2+j] = float64(a[i][2+j])
		}
	}
	return r, true
}

// Matx22dIdentity returns the 2x2 identity matrix.
func Matx22dIdentity() Matx22d {
	var r Matx22d
	for i := 0; i < 2; i++ {
		r[i*2+i] = 1
	}
	return r
}

// Matx23f is a 2x3 matrix of float32 stored row-major, mirroring cv::Matx23f.
type Matx23f [6]float32

// NewMatx23f builds a Matx23f from 6 row-major elements.
func NewMatx23f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32) Matx23f {
	return Matx23f{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx23f) At(i, j int) float32 { return m[i*3+j] }

// Rows returns the row count (2).
func (m Matx23f) Rows() int { return 2 }

// Cols returns the column count (3).
func (m Matx23f) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx23f) Add(o Matx23f) Matx23f {
	var r Matx23f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx23f) Sub(o Matx23f) Matx23f {
	var r Matx23f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx23f) Scale(s float32) Matx23f {
	var r Matx23f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x2 transpose as a Matx32f.
func (m Matx23f) Transpose() Matx32f {
	var t Matx32f
	for i := 0; i < 2; i++ {
		for j := 0; j < 3; j++ {
			t[j*2+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx23f) String() string { return fmt.Sprintf("%v", [6]float32(m)) }

// Matx23d is a 2x3 matrix of float64 stored row-major, mirroring cv::Matx23d.
type Matx23d [6]float64

// NewMatx23d builds a Matx23d from 6 row-major elements.
func NewMatx23d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64) Matx23d {
	return Matx23d{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx23d) At(i, j int) float64 { return m[i*3+j] }

// Rows returns the row count (2).
func (m Matx23d) Rows() int { return 2 }

// Cols returns the column count (3).
func (m Matx23d) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx23d) Add(o Matx23d) Matx23d {
	var r Matx23d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx23d) Sub(o Matx23d) Matx23d {
	var r Matx23d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx23d) Scale(s float64) Matx23d {
	var r Matx23d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x2 transpose as a Matx32d.
func (m Matx23d) Transpose() Matx32d {
	var t Matx32d
	for i := 0; i < 2; i++ {
		for j := 0; j < 3; j++ {
			t[j*2+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx23d) String() string { return fmt.Sprintf("%v", [6]float64(m)) }

// Matx32f is a 3x2 matrix of float32 stored row-major, mirroring cv::Matx32f.
type Matx32f [6]float32

// NewMatx32f builds a Matx32f from 6 row-major elements.
func NewMatx32f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32) Matx32f {
	return Matx32f{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx32f) At(i, j int) float32 { return m[i*2+j] }

// Rows returns the row count (3).
func (m Matx32f) Rows() int { return 3 }

// Cols returns the column count (2).
func (m Matx32f) Cols() int { return 2 }

// Add returns the element-wise sum m+o.
func (m Matx32f) Add(o Matx32f) Matx32f {
	var r Matx32f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx32f) Sub(o Matx32f) Matx32f {
	var r Matx32f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx32f) Scale(s float32) Matx32f {
	var r Matx32f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 2x3 transpose as a Matx23f.
func (m Matx32f) Transpose() Matx23f {
	var t Matx23f
	for i := 0; i < 3; i++ {
		for j := 0; j < 2; j++ {
			t[j*3+i] = m[i*2+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx32f) String() string { return fmt.Sprintf("%v", [6]float32(m)) }

// Matx32d is a 3x2 matrix of float64 stored row-major, mirroring cv::Matx32d.
type Matx32d [6]float64

// NewMatx32d builds a Matx32d from 6 row-major elements.
func NewMatx32d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64) Matx32d {
	return Matx32d{e0, e1, e2, e3, e4, e5}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx32d) At(i, j int) float64 { return m[i*2+j] }

// Rows returns the row count (3).
func (m Matx32d) Rows() int { return 3 }

// Cols returns the column count (2).
func (m Matx32d) Cols() int { return 2 }

// Add returns the element-wise sum m+o.
func (m Matx32d) Add(o Matx32d) Matx32d {
	var r Matx32d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx32d) Sub(o Matx32d) Matx32d {
	var r Matx32d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx32d) Scale(s float64) Matx32d {
	var r Matx32d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 2x3 transpose as a Matx23d.
func (m Matx32d) Transpose() Matx23d {
	var t Matx23d
	for i := 0; i < 3; i++ {
		for j := 0; j < 2; j++ {
			t[j*3+i] = m[i*2+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx32d) String() string { return fmt.Sprintf("%v", [6]float64(m)) }

// Matx33f is a 3x3 matrix of float32 stored row-major, mirroring cv::Matx33f.
type Matx33f [9]float32

// NewMatx33f builds a Matx33f from 9 row-major elements.
func NewMatx33f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32, e6 float32, e7 float32, e8 float32) Matx33f {
	return Matx33f{e0, e1, e2, e3, e4, e5, e6, e7, e8}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx33f) At(i, j int) float32 { return m[i*3+j] }

// Rows returns the row count (3).
func (m Matx33f) Rows() int { return 3 }

// Cols returns the column count (3).
func (m Matx33f) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx33f) Add(o Matx33f) Matx33f {
	var r Matx33f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx33f) Sub(o Matx33f) Matx33f {
	var r Matx33f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx33f) Scale(s float32) Matx33f {
	var r Matx33f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x3 transpose as a Matx33f.
func (m Matx33f) Transpose() Matx33f {
	var t Matx33f
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			t[j*3+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx33f) String() string { return fmt.Sprintf("%v", [9]float32(m)) }

// Mul returns the matrix product m*o.
func (m Matx33f) Mul(o Matx33f) Matx33f {
	var r Matx33f
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			var s float32
			for k := 0; k < 3; k++ {
				s += m[i*3+k] * o[k*3+j]
			}
			r[i*3+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx33f) MulVec(v Vec3f) Vec3f {
	var r Vec3f
	for i := 0; i < 3; i++ {
		var s float32
		for k := 0; k < 3; k++ {
			s += m[i*3+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx33f) Trace() float64 {
	var s float64
	for i := 0; i < 3; i++ {
		s += float64(m[i*3+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx33f) Determinant() float64 {
	var a [3][3]float64
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			a[i][j] = float64(m[i*3+j])
		}
	}
	det := 1.0
	for col := 0; col < 3; col++ {
		p := col
		for rr := col + 1; rr < 3; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 3; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 3; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx33f) Inverse() (Matx33f, bool) {
	var a [3][6]float64
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			a[i][j] = float64(m[i*3+j])
		}
		a[i][3+i] = 1
	}
	for col := 0; col < 3; col++ {
		p := col
		for rr := col + 1; rr < 3; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx33f
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 6; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 3; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 6; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx33f
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			r[i*3+j] = float32(a[i][3+j])
		}
	}
	return r, true
}

// Matx33fIdentity returns the 3x3 identity matrix.
func Matx33fIdentity() Matx33f {
	var r Matx33f
	for i := 0; i < 3; i++ {
		r[i*3+i] = 1
	}
	return r
}

// Matx33d is a 3x3 matrix of float64 stored row-major, mirroring cv::Matx33d.
type Matx33d [9]float64

// NewMatx33d builds a Matx33d from 9 row-major elements.
func NewMatx33d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64, e6 float64, e7 float64, e8 float64) Matx33d {
	return Matx33d{e0, e1, e2, e3, e4, e5, e6, e7, e8}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx33d) At(i, j int) float64 { return m[i*3+j] }

// Rows returns the row count (3).
func (m Matx33d) Rows() int { return 3 }

// Cols returns the column count (3).
func (m Matx33d) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx33d) Add(o Matx33d) Matx33d {
	var r Matx33d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx33d) Sub(o Matx33d) Matx33d {
	var r Matx33d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx33d) Scale(s float64) Matx33d {
	var r Matx33d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x3 transpose as a Matx33d.
func (m Matx33d) Transpose() Matx33d {
	var t Matx33d
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			t[j*3+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx33d) String() string { return fmt.Sprintf("%v", [9]float64(m)) }

// Mul returns the matrix product m*o.
func (m Matx33d) Mul(o Matx33d) Matx33d {
	var r Matx33d
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			var s float64
			for k := 0; k < 3; k++ {
				s += m[i*3+k] * o[k*3+j]
			}
			r[i*3+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx33d) MulVec(v Vec3d) Vec3d {
	var r Vec3d
	for i := 0; i < 3; i++ {
		var s float64
		for k := 0; k < 3; k++ {
			s += m[i*3+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx33d) Trace() float64 {
	var s float64
	for i := 0; i < 3; i++ {
		s += float64(m[i*3+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx33d) Determinant() float64 {
	var a [3][3]float64
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			a[i][j] = float64(m[i*3+j])
		}
	}
	det := 1.0
	for col := 0; col < 3; col++ {
		p := col
		for rr := col + 1; rr < 3; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 3; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 3; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx33d) Inverse() (Matx33d, bool) {
	var a [3][6]float64
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			a[i][j] = float64(m[i*3+j])
		}
		a[i][3+i] = 1
	}
	for col := 0; col < 3; col++ {
		p := col
		for rr := col + 1; rr < 3; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx33d
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 6; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 3; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 6; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx33d
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			r[i*3+j] = float64(a[i][3+j])
		}
	}
	return r, true
}

// Matx33dIdentity returns the 3x3 identity matrix.
func Matx33dIdentity() Matx33d {
	var r Matx33d
	for i := 0; i < 3; i++ {
		r[i*3+i] = 1
	}
	return r
}

// Matx34f is a 3x4 matrix of float32 stored row-major, mirroring cv::Matx34f.
type Matx34f [12]float32

// NewMatx34f builds a Matx34f from 12 row-major elements.
func NewMatx34f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32, e6 float32, e7 float32, e8 float32, e9 float32, e10 float32, e11 float32) Matx34f {
	return Matx34f{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx34f) At(i, j int) float32 { return m[i*4+j] }

// Rows returns the row count (3).
func (m Matx34f) Rows() int { return 3 }

// Cols returns the column count (4).
func (m Matx34f) Cols() int { return 4 }

// Add returns the element-wise sum m+o.
func (m Matx34f) Add(o Matx34f) Matx34f {
	var r Matx34f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx34f) Sub(o Matx34f) Matx34f {
	var r Matx34f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx34f) Scale(s float32) Matx34f {
	var r Matx34f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 4x3 transpose as a Matx43f.
func (m Matx34f) Transpose() Matx43f {
	var t Matx43f
	for i := 0; i < 3; i++ {
		for j := 0; j < 4; j++ {
			t[j*3+i] = m[i*4+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx34f) String() string { return fmt.Sprintf("%v", [12]float32(m)) }

// Matx34d is a 3x4 matrix of float64 stored row-major, mirroring cv::Matx34d.
type Matx34d [12]float64

// NewMatx34d builds a Matx34d from 12 row-major elements.
func NewMatx34d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64, e6 float64, e7 float64, e8 float64, e9 float64, e10 float64, e11 float64) Matx34d {
	return Matx34d{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx34d) At(i, j int) float64 { return m[i*4+j] }

// Rows returns the row count (3).
func (m Matx34d) Rows() int { return 3 }

// Cols returns the column count (4).
func (m Matx34d) Cols() int { return 4 }

// Add returns the element-wise sum m+o.
func (m Matx34d) Add(o Matx34d) Matx34d {
	var r Matx34d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx34d) Sub(o Matx34d) Matx34d {
	var r Matx34d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx34d) Scale(s float64) Matx34d {
	var r Matx34d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 4x3 transpose as a Matx43d.
func (m Matx34d) Transpose() Matx43d {
	var t Matx43d
	for i := 0; i < 3; i++ {
		for j := 0; j < 4; j++ {
			t[j*3+i] = m[i*4+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx34d) String() string { return fmt.Sprintf("%v", [12]float64(m)) }

// Matx43f is a 4x3 matrix of float32 stored row-major, mirroring cv::Matx43f.
type Matx43f [12]float32

// NewMatx43f builds a Matx43f from 12 row-major elements.
func NewMatx43f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32, e6 float32, e7 float32, e8 float32, e9 float32, e10 float32, e11 float32) Matx43f {
	return Matx43f{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx43f) At(i, j int) float32 { return m[i*3+j] }

// Rows returns the row count (4).
func (m Matx43f) Rows() int { return 4 }

// Cols returns the column count (3).
func (m Matx43f) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx43f) Add(o Matx43f) Matx43f {
	var r Matx43f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx43f) Sub(o Matx43f) Matx43f {
	var r Matx43f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx43f) Scale(s float32) Matx43f {
	var r Matx43f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x4 transpose as a Matx34f.
func (m Matx43f) Transpose() Matx34f {
	var t Matx34f
	for i := 0; i < 4; i++ {
		for j := 0; j < 3; j++ {
			t[j*4+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx43f) String() string { return fmt.Sprintf("%v", [12]float32(m)) }

// Matx43d is a 4x3 matrix of float64 stored row-major, mirroring cv::Matx43d.
type Matx43d [12]float64

// NewMatx43d builds a Matx43d from 12 row-major elements.
func NewMatx43d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64, e6 float64, e7 float64, e8 float64, e9 float64, e10 float64, e11 float64) Matx43d {
	return Matx43d{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx43d) At(i, j int) float64 { return m[i*3+j] }

// Rows returns the row count (4).
func (m Matx43d) Rows() int { return 4 }

// Cols returns the column count (3).
func (m Matx43d) Cols() int { return 3 }

// Add returns the element-wise sum m+o.
func (m Matx43d) Add(o Matx43d) Matx43d {
	var r Matx43d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx43d) Sub(o Matx43d) Matx43d {
	var r Matx43d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx43d) Scale(s float64) Matx43d {
	var r Matx43d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 3x4 transpose as a Matx34d.
func (m Matx43d) Transpose() Matx34d {
	var t Matx34d
	for i := 0; i < 4; i++ {
		for j := 0; j < 3; j++ {
			t[j*4+i] = m[i*3+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx43d) String() string { return fmt.Sprintf("%v", [12]float64(m)) }

// Matx44f is a 4x4 matrix of float32 stored row-major, mirroring cv::Matx44f.
type Matx44f [16]float32

// NewMatx44f builds a Matx44f from 16 row-major elements.
func NewMatx44f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32, e6 float32, e7 float32, e8 float32, e9 float32, e10 float32, e11 float32, e12 float32, e13 float32, e14 float32, e15 float32) Matx44f {
	return Matx44f{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx44f) At(i, j int) float32 { return m[i*4+j] }

// Rows returns the row count (4).
func (m Matx44f) Rows() int { return 4 }

// Cols returns the column count (4).
func (m Matx44f) Cols() int { return 4 }

// Add returns the element-wise sum m+o.
func (m Matx44f) Add(o Matx44f) Matx44f {
	var r Matx44f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx44f) Sub(o Matx44f) Matx44f {
	var r Matx44f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx44f) Scale(s float32) Matx44f {
	var r Matx44f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 4x4 transpose as a Matx44f.
func (m Matx44f) Transpose() Matx44f {
	var t Matx44f
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			t[j*4+i] = m[i*4+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx44f) String() string { return fmt.Sprintf("%v", [16]float32(m)) }

// Mul returns the matrix product m*o.
func (m Matx44f) Mul(o Matx44f) Matx44f {
	var r Matx44f
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			var s float32
			for k := 0; k < 4; k++ {
				s += m[i*4+k] * o[k*4+j]
			}
			r[i*4+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx44f) MulVec(v Vec4f) Vec4f {
	var r Vec4f
	for i := 0; i < 4; i++ {
		var s float32
		for k := 0; k < 4; k++ {
			s += m[i*4+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx44f) Trace() float64 {
	var s float64
	for i := 0; i < 4; i++ {
		s += float64(m[i*4+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx44f) Determinant() float64 {
	var a [4][4]float64
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			a[i][j] = float64(m[i*4+j])
		}
	}
	det := 1.0
	for col := 0; col < 4; col++ {
		p := col
		for rr := col + 1; rr < 4; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 4; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 4; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx44f) Inverse() (Matx44f, bool) {
	var a [4][8]float64
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			a[i][j] = float64(m[i*4+j])
		}
		a[i][4+i] = 1
	}
	for col := 0; col < 4; col++ {
		p := col
		for rr := col + 1; rr < 4; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx44f
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 8; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 4; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 8; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx44f
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			r[i*4+j] = float32(a[i][4+j])
		}
	}
	return r, true
}

// Matx44fIdentity returns the 4x4 identity matrix.
func Matx44fIdentity() Matx44f {
	var r Matx44f
	for i := 0; i < 4; i++ {
		r[i*4+i] = 1
	}
	return r
}

// Matx44d is a 4x4 matrix of float64 stored row-major, mirroring cv::Matx44d.
type Matx44d [16]float64

// NewMatx44d builds a Matx44d from 16 row-major elements.
func NewMatx44d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64, e6 float64, e7 float64, e8 float64, e9 float64, e10 float64, e11 float64, e12 float64, e13 float64, e14 float64, e15 float64) Matx44d {
	return Matx44d{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx44d) At(i, j int) float64 { return m[i*4+j] }

// Rows returns the row count (4).
func (m Matx44d) Rows() int { return 4 }

// Cols returns the column count (4).
func (m Matx44d) Cols() int { return 4 }

// Add returns the element-wise sum m+o.
func (m Matx44d) Add(o Matx44d) Matx44d {
	var r Matx44d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx44d) Sub(o Matx44d) Matx44d {
	var r Matx44d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx44d) Scale(s float64) Matx44d {
	var r Matx44d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 4x4 transpose as a Matx44d.
func (m Matx44d) Transpose() Matx44d {
	var t Matx44d
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			t[j*4+i] = m[i*4+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx44d) String() string { return fmt.Sprintf("%v", [16]float64(m)) }

// Mul returns the matrix product m*o.
func (m Matx44d) Mul(o Matx44d) Matx44d {
	var r Matx44d
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			var s float64
			for k := 0; k < 4; k++ {
				s += m[i*4+k] * o[k*4+j]
			}
			r[i*4+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx44d) MulVec(v Vec4d) Vec4d {
	var r Vec4d
	for i := 0; i < 4; i++ {
		var s float64
		for k := 0; k < 4; k++ {
			s += m[i*4+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx44d) Trace() float64 {
	var s float64
	for i := 0; i < 4; i++ {
		s += float64(m[i*4+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx44d) Determinant() float64 {
	var a [4][4]float64
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			a[i][j] = float64(m[i*4+j])
		}
	}
	det := 1.0
	for col := 0; col < 4; col++ {
		p := col
		for rr := col + 1; rr < 4; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 4; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 4; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx44d) Inverse() (Matx44d, bool) {
	var a [4][8]float64
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			a[i][j] = float64(m[i*4+j])
		}
		a[i][4+i] = 1
	}
	for col := 0; col < 4; col++ {
		p := col
		for rr := col + 1; rr < 4; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx44d
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 8; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 4; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 8; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx44d
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			r[i*4+j] = float64(a[i][4+j])
		}
	}
	return r, true
}

// Matx44dIdentity returns the 4x4 identity matrix.
func Matx44dIdentity() Matx44d {
	var r Matx44d
	for i := 0; i < 4; i++ {
		r[i*4+i] = 1
	}
	return r
}

// Matx66f is a 6x6 matrix of float32 stored row-major, mirroring cv::Matx66f.
type Matx66f [36]float32

// NewMatx66f builds a Matx66f from 36 row-major elements.
func NewMatx66f(e0 float32, e1 float32, e2 float32, e3 float32, e4 float32, e5 float32, e6 float32, e7 float32, e8 float32, e9 float32, e10 float32, e11 float32, e12 float32, e13 float32, e14 float32, e15 float32, e16 float32, e17 float32, e18 float32, e19 float32, e20 float32, e21 float32, e22 float32, e23 float32, e24 float32, e25 float32, e26 float32, e27 float32, e28 float32, e29 float32, e30 float32, e31 float32, e32 float32, e33 float32, e34 float32, e35 float32) Matx66f {
	return Matx66f{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx66f) At(i, j int) float32 { return m[i*6+j] }

// Rows returns the row count (6).
func (m Matx66f) Rows() int { return 6 }

// Cols returns the column count (6).
func (m Matx66f) Cols() int { return 6 }

// Add returns the element-wise sum m+o.
func (m Matx66f) Add(o Matx66f) Matx66f {
	var r Matx66f
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx66f) Sub(o Matx66f) Matx66f {
	var r Matx66f
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx66f) Scale(s float32) Matx66f {
	var r Matx66f
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 6x6 transpose as a Matx66f.
func (m Matx66f) Transpose() Matx66f {
	var t Matx66f
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			t[j*6+i] = m[i*6+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx66f) String() string { return fmt.Sprintf("%v", [36]float32(m)) }

// Mul returns the matrix product m*o.
func (m Matx66f) Mul(o Matx66f) Matx66f {
	var r Matx66f
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			var s float32
			for k := 0; k < 6; k++ {
				s += m[i*6+k] * o[k*6+j]
			}
			r[i*6+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx66f) MulVec(v Vec6f) Vec6f {
	var r Vec6f
	for i := 0; i < 6; i++ {
		var s float32
		for k := 0; k < 6; k++ {
			s += m[i*6+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx66f) Trace() float64 {
	var s float64
	for i := 0; i < 6; i++ {
		s += float64(m[i*6+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx66f) Determinant() float64 {
	var a [6][6]float64
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			a[i][j] = float64(m[i*6+j])
		}
	}
	det := 1.0
	for col := 0; col < 6; col++ {
		p := col
		for rr := col + 1; rr < 6; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 6; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 6; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx66f) Inverse() (Matx66f, bool) {
	var a [6][12]float64
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			a[i][j] = float64(m[i*6+j])
		}
		a[i][6+i] = 1
	}
	for col := 0; col < 6; col++ {
		p := col
		for rr := col + 1; rr < 6; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx66f
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 12; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 6; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 12; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx66f
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			r[i*6+j] = float32(a[i][6+j])
		}
	}
	return r, true
}

// Matx66fIdentity returns the 6x6 identity matrix.
func Matx66fIdentity() Matx66f {
	var r Matx66f
	for i := 0; i < 6; i++ {
		r[i*6+i] = 1
	}
	return r
}

// Matx66d is a 6x6 matrix of float64 stored row-major, mirroring cv::Matx66d.
type Matx66d [36]float64

// NewMatx66d builds a Matx66d from 36 row-major elements.
func NewMatx66d(e0 float64, e1 float64, e2 float64, e3 float64, e4 float64, e5 float64, e6 float64, e7 float64, e8 float64, e9 float64, e10 float64, e11 float64, e12 float64, e13 float64, e14 float64, e15 float64, e16 float64, e17 float64, e18 float64, e19 float64, e20 float64, e21 float64, e22 float64, e23 float64, e24 float64, e25 float64, e26 float64, e27 float64, e28 float64, e29 float64, e30 float64, e31 float64, e32 float64, e33 float64, e34 float64, e35 float64) Matx66d {
	return Matx66d{e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35}
}

// At returns the element at row i, column j (0-indexed).
func (m Matx66d) At(i, j int) float64 { return m[i*6+j] }

// Rows returns the row count (6).
func (m Matx66d) Rows() int { return 6 }

// Cols returns the column count (6).
func (m Matx66d) Cols() int { return 6 }

// Add returns the element-wise sum m+o.
func (m Matx66d) Add(o Matx66d) Matx66d {
	var r Matx66d
	for i := range m {
		r[i] = m[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference m-o.
func (m Matx66d) Sub(o Matx66d) Matx66d {
	var r Matx66d
	for i := range m {
		r[i] = m[i] - o[i]
	}
	return r
}

// Scale returns the matrix with every element multiplied by s.
func (m Matx66d) Scale(s float64) Matx66d {
	var r Matx66d
	for i := range m {
		r[i] = m[i] * s
	}
	return r
}

// Transpose returns the 6x6 transpose as a Matx66d.
func (m Matx66d) Transpose() Matx66d {
	var t Matx66d
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			t[j*6+i] = m[i*6+j]
		}
	}
	return t
}

// String renders the matrix elements in row-major order.
func (m Matx66d) String() string { return fmt.Sprintf("%v", [36]float64(m)) }

// Mul returns the matrix product m*o.
func (m Matx66d) Mul(o Matx66d) Matx66d {
	var r Matx66d
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			var s float64
			for k := 0; k < 6; k++ {
				s += m[i*6+k] * o[k*6+j]
			}
			r[i*6+j] = s
		}
	}
	return r
}

// MulVec returns the matrix-vector product m*v.
func (m Matx66d) MulVec(v Vec6d) Vec6d {
	var r Vec6d
	for i := 0; i < 6; i++ {
		var s float64
		for k := 0; k < 6; k++ {
			s += m[i*6+k] * v[k]
		}
		r[i] = s
	}
	return r
}

// Trace returns the sum of the diagonal elements as float64.
func (m Matx66d) Trace() float64 {
	var s float64
	for i := 0; i < 6; i++ {
		s += float64(m[i*6+i])
	}
	return s
}

// Determinant returns the determinant computed in float64 by Gaussian
// elimination with partial pivoting.
func (m Matx66d) Determinant() float64 {
	var a [6][6]float64
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			a[i][j] = float64(m[i*6+j])
		}
	}
	det := 1.0
	for col := 0; col < 6; col++ {
		p := col
		for rr := col + 1; rr < 6; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			return 0
		}
		if p != col {
			a[p], a[col] = a[col], a[p]
			det = -det
		}
		det *= a[col][col]
		for rr := col + 1; rr < 6; rr++ {
			f := a[rr][col] / a[col][col]
			for cc := col; cc < 6; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	return det
}

// Inverse returns the matrix inverse and true, or the zero matrix and
// false when the matrix is singular. Computation is in float64.
func (m Matx66d) Inverse() (Matx66d, bool) {
	var a [6][12]float64
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			a[i][j] = float64(m[i*6+j])
		}
		a[i][6+i] = 1
	}
	for col := 0; col < 6; col++ {
		p := col
		for rr := col + 1; rr < 6; rr++ {
			if matxAbs(a[rr][col]) > matxAbs(a[p][col]) {
				p = rr
			}
		}
		if a[p][col] == 0 {
			var z Matx66d
			return z, false
		}
		a[p], a[col] = a[col], a[p]
		pv := a[col][col]
		for cc := 0; cc < 12; cc++ {
			a[col][cc] /= pv
		}
		for rr := 0; rr < 6; rr++ {
			if rr == col {
				continue
			}
			f := a[rr][col]
			for cc := 0; cc < 12; cc++ {
				a[rr][cc] -= f * a[col][cc]
			}
		}
	}
	var r Matx66d
	for i := 0; i < 6; i++ {
		for j := 0; j < 6; j++ {
			r[i*6+j] = float64(a[i][6+j])
		}
	}
	return r, true
}

// Matx66dIdentity returns the 6x6 identity matrix.
func Matx66dIdentity() Matx66d {
	var r Matx66d
	for i := 0; i < 6; i++ {
		r[i*6+i] = 1
	}
	return r
}

// matxAbs returns the absolute value of x.
func matxAbs(x float64) float64 {
	if x < 0 {
		return -x
	}
	return x
}
