// Code generated by core value-type builder. DO NOT EDIT by hand.

package core

import (
	"fmt"
	"math"
)

// Vec2b is a fixed-length vector of 2 uint8 values, mirroring
// OpenCV's cv::Vec2b. Elements are stored in index order.
type Vec2b [2]uint8

// NewVec2b builds a Vec2b from its 2 components.
func NewVec2b(x uint8, y uint8) Vec2b {
	return Vec2b{x, y}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec2b) At(i int) uint8 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; uint8 arithmetic wraps).
func (v Vec2b) Add(o Vec2b) Vec2b {
	var r Vec2b
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec2b) Sub(o Vec2b) Vec2b {
	var r Vec2b
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec2b) Mul(s uint8) Vec2b {
	var r Vec2b
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec2b) MulElem(o Vec2b) Vec2b {
	var r Vec2b
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec2b) Dot(o Vec2b) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec2b) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec2b) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec2b) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec2b) Equals(o Vec2b) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec2b) String() string { return fmt.Sprintf("%v", [2]uint8(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec2b) ToSlice() []uint8 { s := make([]uint8, 2); copy(s, v[:]); return s }

// ToVec2f converts the components to float32.
func (v Vec2b) ToVec2f() Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec2d converts the components to float64.
func (v Vec2b) ToVec2d() Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec3b is a fixed-length vector of 3 uint8 values, mirroring
// OpenCV's cv::Vec3b. Elements are stored in index order.
type Vec3b [3]uint8

// NewVec3b builds a Vec3b from its 3 components.
func NewVec3b(x uint8, y uint8, z uint8) Vec3b {
	return Vec3b{x, y, z}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec3b) At(i int) uint8 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; uint8 arithmetic wraps).
func (v Vec3b) Add(o Vec3b) Vec3b {
	var r Vec3b
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec3b) Sub(o Vec3b) Vec3b {
	var r Vec3b
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec3b) Mul(s uint8) Vec3b {
	var r Vec3b
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec3b) MulElem(o Vec3b) Vec3b {
	var r Vec3b
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec3b) Dot(o Vec3b) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec3b) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec3b) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec3b) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec3b) Equals(o Vec3b) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Cross returns the 3D cross product v x o.
func (v Vec3b) Cross(o Vec3b) Vec3b {
	return Vec3b{
		v[1]*o[2] - v[2]*o[1],
		v[2]*o[0] - v[0]*o[2],
		v[0]*o[1] - v[1]*o[0],
	}
}

// String renders the vector as [a, b, ...].
func (v Vec3b) String() string { return fmt.Sprintf("%v", [3]uint8(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec3b) ToSlice() []uint8 { s := make([]uint8, 3); copy(s, v[:]); return s }

// ToVec3f converts the components to float32.
func (v Vec3b) ToVec3f() Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec3d converts the components to float64.
func (v Vec3b) ToVec3d() Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec4b is a fixed-length vector of 4 uint8 values, mirroring
// OpenCV's cv::Vec4b. Elements are stored in index order.
type Vec4b [4]uint8

// NewVec4b builds a Vec4b from its 4 components.
func NewVec4b(x uint8, y uint8, z uint8, w uint8) Vec4b {
	return Vec4b{x, y, z, w}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec4b) At(i int) uint8 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; uint8 arithmetic wraps).
func (v Vec4b) Add(o Vec4b) Vec4b {
	var r Vec4b
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec4b) Sub(o Vec4b) Vec4b {
	var r Vec4b
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec4b) Mul(s uint8) Vec4b {
	var r Vec4b
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec4b) MulElem(o Vec4b) Vec4b {
	var r Vec4b
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec4b) Dot(o Vec4b) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec4b) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec4b) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec4b) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec4b) Equals(o Vec4b) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec4b) String() string { return fmt.Sprintf("%v", [4]uint8(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec4b) ToSlice() []uint8 { s := make([]uint8, 4); copy(s, v[:]); return s }

// ToVec4f converts the components to float32.
func (v Vec4b) ToVec4f() Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec4d converts the components to float64.
func (v Vec4b) ToVec4d() Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec2s is a fixed-length vector of 2 int16 values, mirroring
// OpenCV's cv::Vec2s. Elements are stored in index order.
type Vec2s [2]int16

// NewVec2s builds a Vec2s from its 2 components.
func NewVec2s(x int16, y int16) Vec2s {
	return Vec2s{x, y}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec2s) At(i int) int16 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int16 arithmetic wraps).
func (v Vec2s) Add(o Vec2s) Vec2s {
	var r Vec2s
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec2s) Sub(o Vec2s) Vec2s {
	var r Vec2s
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec2s) Mul(s int16) Vec2s {
	var r Vec2s
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec2s) MulElem(o Vec2s) Vec2s {
	var r Vec2s
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec2s) Dot(o Vec2s) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec2s) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec2s) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec2s) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec2s) Equals(o Vec2s) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec2s) String() string { return fmt.Sprintf("%v", [2]int16(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec2s) ToSlice() []int16 { s := make([]int16, 2); copy(s, v[:]); return s }

// ToVec2f converts the components to float32.
func (v Vec2s) ToVec2f() Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec2d converts the components to float64.
func (v Vec2s) ToVec2d() Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec3s is a fixed-length vector of 3 int16 values, mirroring
// OpenCV's cv::Vec3s. Elements are stored in index order.
type Vec3s [3]int16

// NewVec3s builds a Vec3s from its 3 components.
func NewVec3s(x int16, y int16, z int16) Vec3s {
	return Vec3s{x, y, z}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec3s) At(i int) int16 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int16 arithmetic wraps).
func (v Vec3s) Add(o Vec3s) Vec3s {
	var r Vec3s
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec3s) Sub(o Vec3s) Vec3s {
	var r Vec3s
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec3s) Mul(s int16) Vec3s {
	var r Vec3s
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec3s) MulElem(o Vec3s) Vec3s {
	var r Vec3s
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec3s) Dot(o Vec3s) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec3s) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec3s) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec3s) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec3s) Equals(o Vec3s) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Cross returns the 3D cross product v x o.
func (v Vec3s) Cross(o Vec3s) Vec3s {
	return Vec3s{
		v[1]*o[2] - v[2]*o[1],
		v[2]*o[0] - v[0]*o[2],
		v[0]*o[1] - v[1]*o[0],
	}
}

// String renders the vector as [a, b, ...].
func (v Vec3s) String() string { return fmt.Sprintf("%v", [3]int16(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec3s) ToSlice() []int16 { s := make([]int16, 3); copy(s, v[:]); return s }

// ToVec3f converts the components to float32.
func (v Vec3s) ToVec3f() Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec3d converts the components to float64.
func (v Vec3s) ToVec3d() Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec4s is a fixed-length vector of 4 int16 values, mirroring
// OpenCV's cv::Vec4s. Elements are stored in index order.
type Vec4s [4]int16

// NewVec4s builds a Vec4s from its 4 components.
func NewVec4s(x int16, y int16, z int16, w int16) Vec4s {
	return Vec4s{x, y, z, w}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec4s) At(i int) int16 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int16 arithmetic wraps).
func (v Vec4s) Add(o Vec4s) Vec4s {
	var r Vec4s
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec4s) Sub(o Vec4s) Vec4s {
	var r Vec4s
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec4s) Mul(s int16) Vec4s {
	var r Vec4s
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec4s) MulElem(o Vec4s) Vec4s {
	var r Vec4s
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec4s) Dot(o Vec4s) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec4s) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec4s) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec4s) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec4s) Equals(o Vec4s) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec4s) String() string { return fmt.Sprintf("%v", [4]int16(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec4s) ToSlice() []int16 { s := make([]int16, 4); copy(s, v[:]); return s }

// ToVec4f converts the components to float32.
func (v Vec4s) ToVec4f() Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec4d converts the components to float64.
func (v Vec4s) ToVec4d() Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec2w is a fixed-length vector of 2 uint16 values, mirroring
// OpenCV's cv::Vec2w. Elements are stored in index order.
type Vec2w [2]uint16

// NewVec2w builds a Vec2w from its 2 components.
func NewVec2w(x uint16, y uint16) Vec2w {
	return Vec2w{x, y}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec2w) At(i int) uint16 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; uint16 arithmetic wraps).
func (v Vec2w) Add(o Vec2w) Vec2w {
	var r Vec2w
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec2w) Sub(o Vec2w) Vec2w {
	var r Vec2w
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec2w) Mul(s uint16) Vec2w {
	var r Vec2w
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec2w) MulElem(o Vec2w) Vec2w {
	var r Vec2w
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec2w) Dot(o Vec2w) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec2w) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec2w) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec2w) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec2w) Equals(o Vec2w) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec2w) String() string { return fmt.Sprintf("%v", [2]uint16(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec2w) ToSlice() []uint16 { s := make([]uint16, 2); copy(s, v[:]); return s }

// ToVec2f converts the components to float32.
func (v Vec2w) ToVec2f() Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec2d converts the components to float64.
func (v Vec2w) ToVec2d() Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec3w is a fixed-length vector of 3 uint16 values, mirroring
// OpenCV's cv::Vec3w. Elements are stored in index order.
type Vec3w [3]uint16

// NewVec3w builds a Vec3w from its 3 components.
func NewVec3w(x uint16, y uint16, z uint16) Vec3w {
	return Vec3w{x, y, z}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec3w) At(i int) uint16 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; uint16 arithmetic wraps).
func (v Vec3w) Add(o Vec3w) Vec3w {
	var r Vec3w
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec3w) Sub(o Vec3w) Vec3w {
	var r Vec3w
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec3w) Mul(s uint16) Vec3w {
	var r Vec3w
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec3w) MulElem(o Vec3w) Vec3w {
	var r Vec3w
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec3w) Dot(o Vec3w) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec3w) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec3w) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec3w) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec3w) Equals(o Vec3w) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Cross returns the 3D cross product v x o.
func (v Vec3w) Cross(o Vec3w) Vec3w {
	return Vec3w{
		v[1]*o[2] - v[2]*o[1],
		v[2]*o[0] - v[0]*o[2],
		v[0]*o[1] - v[1]*o[0],
	}
}

// String renders the vector as [a, b, ...].
func (v Vec3w) String() string { return fmt.Sprintf("%v", [3]uint16(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec3w) ToSlice() []uint16 { s := make([]uint16, 3); copy(s, v[:]); return s }

// ToVec3f converts the components to float32.
func (v Vec3w) ToVec3f() Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec3d converts the components to float64.
func (v Vec3w) ToVec3d() Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec4w is a fixed-length vector of 4 uint16 values, mirroring
// OpenCV's cv::Vec4w. Elements are stored in index order.
type Vec4w [4]uint16

// NewVec4w builds a Vec4w from its 4 components.
func NewVec4w(x uint16, y uint16, z uint16, w uint16) Vec4w {
	return Vec4w{x, y, z, w}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec4w) At(i int) uint16 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; uint16 arithmetic wraps).
func (v Vec4w) Add(o Vec4w) Vec4w {
	var r Vec4w
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec4w) Sub(o Vec4w) Vec4w {
	var r Vec4w
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec4w) Mul(s uint16) Vec4w {
	var r Vec4w
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec4w) MulElem(o Vec4w) Vec4w {
	var r Vec4w
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec4w) Dot(o Vec4w) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec4w) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec4w) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec4w) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec4w) Equals(o Vec4w) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec4w) String() string { return fmt.Sprintf("%v", [4]uint16(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec4w) ToSlice() []uint16 { s := make([]uint16, 4); copy(s, v[:]); return s }

// ToVec4f converts the components to float32.
func (v Vec4w) ToVec4f() Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec4d converts the components to float64.
func (v Vec4w) ToVec4d() Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec2i is a fixed-length vector of 2 int values, mirroring
// OpenCV's cv::Vec2i. Elements are stored in index order.
type Vec2i [2]int

// NewVec2i builds a Vec2i from its 2 components.
func NewVec2i(x int, y int) Vec2i {
	return Vec2i{x, y}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec2i) At(i int) int { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int arithmetic wraps).
func (v Vec2i) Add(o Vec2i) Vec2i {
	var r Vec2i
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec2i) Sub(o Vec2i) Vec2i {
	var r Vec2i
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec2i) Mul(s int) Vec2i {
	var r Vec2i
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec2i) MulElem(o Vec2i) Vec2i {
	var r Vec2i
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec2i) Dot(o Vec2i) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec2i) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec2i) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec2i) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec2i) Equals(o Vec2i) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec2i) String() string { return fmt.Sprintf("%v", [2]int(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec2i) ToSlice() []int { s := make([]int, 2); copy(s, v[:]); return s }

// ToVec2f converts the components to float32.
func (v Vec2i) ToVec2f() Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec2d converts the components to float64.
func (v Vec2i) ToVec2d() Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec3i is a fixed-length vector of 3 int values, mirroring
// OpenCV's cv::Vec3i. Elements are stored in index order.
type Vec3i [3]int

// NewVec3i builds a Vec3i from its 3 components.
func NewVec3i(x int, y int, z int) Vec3i {
	return Vec3i{x, y, z}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec3i) At(i int) int { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int arithmetic wraps).
func (v Vec3i) Add(o Vec3i) Vec3i {
	var r Vec3i
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec3i) Sub(o Vec3i) Vec3i {
	var r Vec3i
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec3i) Mul(s int) Vec3i {
	var r Vec3i
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec3i) MulElem(o Vec3i) Vec3i {
	var r Vec3i
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec3i) Dot(o Vec3i) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec3i) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec3i) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec3i) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec3i) Equals(o Vec3i) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Cross returns the 3D cross product v x o.
func (v Vec3i) Cross(o Vec3i) Vec3i {
	return Vec3i{
		v[1]*o[2] - v[2]*o[1],
		v[2]*o[0] - v[0]*o[2],
		v[0]*o[1] - v[1]*o[0],
	}
}

// String renders the vector as [a, b, ...].
func (v Vec3i) String() string { return fmt.Sprintf("%v", [3]int(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec3i) ToSlice() []int { s := make([]int, 3); copy(s, v[:]); return s }

// ToVec3f converts the components to float32.
func (v Vec3i) ToVec3f() Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec3d converts the components to float64.
func (v Vec3i) ToVec3d() Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec4i is a fixed-length vector of 4 int values, mirroring
// OpenCV's cv::Vec4i. Elements are stored in index order.
type Vec4i [4]int

// NewVec4i builds a Vec4i from its 4 components.
func NewVec4i(x int, y int, z int, w int) Vec4i {
	return Vec4i{x, y, z, w}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec4i) At(i int) int { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int arithmetic wraps).
func (v Vec4i) Add(o Vec4i) Vec4i {
	var r Vec4i
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec4i) Sub(o Vec4i) Vec4i {
	var r Vec4i
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec4i) Mul(s int) Vec4i {
	var r Vec4i
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec4i) MulElem(o Vec4i) Vec4i {
	var r Vec4i
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec4i) Dot(o Vec4i) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec4i) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec4i) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec4i) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec4i) Equals(o Vec4i) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec4i) String() string { return fmt.Sprintf("%v", [4]int(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec4i) ToSlice() []int { s := make([]int, 4); copy(s, v[:]); return s }

// ToVec4f converts the components to float32.
func (v Vec4i) ToVec4f() Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec4d converts the components to float64.
func (v Vec4i) ToVec4d() Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec6i is a fixed-length vector of 6 int values, mirroring
// OpenCV's cv::Vec6i. Elements are stored in index order.
type Vec6i [6]int

// NewVec6i builds a Vec6i from its 6 components.
func NewVec6i(x int, y int, z int, w int, a int, b int) Vec6i {
	return Vec6i{x, y, z, w, a, b}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec6i) At(i int) int { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int arithmetic wraps).
func (v Vec6i) Add(o Vec6i) Vec6i {
	var r Vec6i
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec6i) Sub(o Vec6i) Vec6i {
	var r Vec6i
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec6i) Mul(s int) Vec6i {
	var r Vec6i
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec6i) MulElem(o Vec6i) Vec6i {
	var r Vec6i
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec6i) Dot(o Vec6i) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec6i) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec6i) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec6i) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec6i) Equals(o Vec6i) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec6i) String() string { return fmt.Sprintf("%v", [6]int(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec6i) ToSlice() []int { s := make([]int, 6); copy(s, v[:]); return s }

// ToVec6f converts the components to float32.
func (v Vec6i) ToVec6f() Vec6f {
	var r Vec6f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// ToVec6d converts the components to float64.
func (v Vec6i) ToVec6d() Vec6d {
	var r Vec6d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec8i is a fixed-length vector of 8 int values, mirroring
// OpenCV's cv::Vec8i. Elements are stored in index order.
type Vec8i [8]int

// NewVec8i builds a Vec8i from its 8 components.
func NewVec8i(x int, y int, z int, w int, a int, b int, g int, h int) Vec8i {
	return Vec8i{x, y, z, w, a, b, g, h}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec8i) At(i int) int { return v[i] }

// Add returns the element-wise sum v+o (no saturation; int arithmetic wraps).
func (v Vec8i) Add(o Vec8i) Vec8i {
	var r Vec8i
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec8i) Sub(o Vec8i) Vec8i {
	var r Vec8i
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec8i) Mul(s int) Vec8i {
	var r Vec8i
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec8i) MulElem(o Vec8i) Vec8i {
	var r Vec8i
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec8i) Dot(o Vec8i) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec8i) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec8i) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec8i) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec8i) Equals(o Vec8i) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// String renders the vector as [a, b, ...].
func (v Vec8i) String() string { return fmt.Sprintf("%v", [8]int(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec8i) ToSlice() []int { s := make([]int, 8); copy(s, v[:]); return s }

// Vec2f is a fixed-length vector of 2 float32 values, mirroring
// OpenCV's cv::Vec2f. Elements are stored in index order.
type Vec2f [2]float32

// NewVec2f builds a Vec2f from its 2 components.
func NewVec2f(x float32, y float32) Vec2f {
	return Vec2f{x, y}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec2f) At(i int) float32 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float32 arithmetic wraps).
func (v Vec2f) Add(o Vec2f) Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec2f) Sub(o Vec2f) Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec2f) Mul(s float32) Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec2f) MulElem(o Vec2f) Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec2f) Dot(o Vec2f) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec2f) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec2f) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec2f) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec2f) Equals(o Vec2f) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec2f) Normalize() Vec2f {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec2f
	for i := range v {
		r[i] = float32(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec2f) String() string { return fmt.Sprintf("%v", [2]float32(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec2f) ToSlice() []float32 { s := make([]float32, 2); copy(s, v[:]); return s }

// ToVec2d converts the components to float64.
func (v Vec2f) ToVec2d() Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec3f is a fixed-length vector of 3 float32 values, mirroring
// OpenCV's cv::Vec3f. Elements are stored in index order.
type Vec3f [3]float32

// NewVec3f builds a Vec3f from its 3 components.
func NewVec3f(x float32, y float32, z float32) Vec3f {
	return Vec3f{x, y, z}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec3f) At(i int) float32 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float32 arithmetic wraps).
func (v Vec3f) Add(o Vec3f) Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec3f) Sub(o Vec3f) Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec3f) Mul(s float32) Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec3f) MulElem(o Vec3f) Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec3f) Dot(o Vec3f) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec3f) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec3f) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec3f) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec3f) Equals(o Vec3f) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Cross returns the 3D cross product v x o.
func (v Vec3f) Cross(o Vec3f) Vec3f {
	return Vec3f{
		v[1]*o[2] - v[2]*o[1],
		v[2]*o[0] - v[0]*o[2],
		v[0]*o[1] - v[1]*o[0],
	}
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec3f) Normalize() Vec3f {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec3f
	for i := range v {
		r[i] = float32(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec3f) String() string { return fmt.Sprintf("%v", [3]float32(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec3f) ToSlice() []float32 { s := make([]float32, 3); copy(s, v[:]); return s }

// ToVec3d converts the components to float64.
func (v Vec3f) ToVec3d() Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec4f is a fixed-length vector of 4 float32 values, mirroring
// OpenCV's cv::Vec4f. Elements are stored in index order.
type Vec4f [4]float32

// NewVec4f builds a Vec4f from its 4 components.
func NewVec4f(x float32, y float32, z float32, w float32) Vec4f {
	return Vec4f{x, y, z, w}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec4f) At(i int) float32 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float32 arithmetic wraps).
func (v Vec4f) Add(o Vec4f) Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec4f) Sub(o Vec4f) Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec4f) Mul(s float32) Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec4f) MulElem(o Vec4f) Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec4f) Dot(o Vec4f) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec4f) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec4f) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec4f) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec4f) Equals(o Vec4f) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec4f) Normalize() Vec4f {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec4f
	for i := range v {
		r[i] = float32(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec4f) String() string { return fmt.Sprintf("%v", [4]float32(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec4f) ToSlice() []float32 { s := make([]float32, 4); copy(s, v[:]); return s }

// ToVec4d converts the components to float64.
func (v Vec4f) ToVec4d() Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec6f is a fixed-length vector of 6 float32 values, mirroring
// OpenCV's cv::Vec6f. Elements are stored in index order.
type Vec6f [6]float32

// NewVec6f builds a Vec6f from its 6 components.
func NewVec6f(x float32, y float32, z float32, w float32, a float32, b float32) Vec6f {
	return Vec6f{x, y, z, w, a, b}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec6f) At(i int) float32 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float32 arithmetic wraps).
func (v Vec6f) Add(o Vec6f) Vec6f {
	var r Vec6f
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec6f) Sub(o Vec6f) Vec6f {
	var r Vec6f
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec6f) Mul(s float32) Vec6f {
	var r Vec6f
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec6f) MulElem(o Vec6f) Vec6f {
	var r Vec6f
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec6f) Dot(o Vec6f) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec6f) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec6f) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec6f) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec6f) Equals(o Vec6f) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec6f) Normalize() Vec6f {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec6f
	for i := range v {
		r[i] = float32(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec6f) String() string { return fmt.Sprintf("%v", [6]float32(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec6f) ToSlice() []float32 { s := make([]float32, 6); copy(s, v[:]); return s }

// ToVec6d converts the components to float64.
func (v Vec6f) ToVec6d() Vec6d {
	var r Vec6d
	for i := range v {
		r[i] = float64(v[i])
	}
	return r
}

// Vec2d is a fixed-length vector of 2 float64 values, mirroring
// OpenCV's cv::Vec2d. Elements are stored in index order.
type Vec2d [2]float64

// NewVec2d builds a Vec2d from its 2 components.
func NewVec2d(x float64, y float64) Vec2d {
	return Vec2d{x, y}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec2d) At(i int) float64 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float64 arithmetic wraps).
func (v Vec2d) Add(o Vec2d) Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec2d) Sub(o Vec2d) Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec2d) Mul(s float64) Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec2d) MulElem(o Vec2d) Vec2d {
	var r Vec2d
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec2d) Dot(o Vec2d) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec2d) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec2d) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec2d) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec2d) Equals(o Vec2d) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec2d) Normalize() Vec2d {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec2d
	for i := range v {
		r[i] = float64(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec2d) String() string { return fmt.Sprintf("%v", [2]float64(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec2d) ToSlice() []float64 { s := make([]float64, 2); copy(s, v[:]); return s }

// ToVec2f converts the components to float32.
func (v Vec2d) ToVec2f() Vec2f {
	var r Vec2f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// Vec3d is a fixed-length vector of 3 float64 values, mirroring
// OpenCV's cv::Vec3d. Elements are stored in index order.
type Vec3d [3]float64

// NewVec3d builds a Vec3d from its 3 components.
func NewVec3d(x float64, y float64, z float64) Vec3d {
	return Vec3d{x, y, z}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec3d) At(i int) float64 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float64 arithmetic wraps).
func (v Vec3d) Add(o Vec3d) Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec3d) Sub(o Vec3d) Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec3d) Mul(s float64) Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec3d) MulElem(o Vec3d) Vec3d {
	var r Vec3d
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec3d) Dot(o Vec3d) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec3d) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec3d) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec3d) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec3d) Equals(o Vec3d) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Cross returns the 3D cross product v x o.
func (v Vec3d) Cross(o Vec3d) Vec3d {
	return Vec3d{
		v[1]*o[2] - v[2]*o[1],
		v[2]*o[0] - v[0]*o[2],
		v[0]*o[1] - v[1]*o[0],
	}
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec3d) Normalize() Vec3d {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec3d
	for i := range v {
		r[i] = float64(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec3d) String() string { return fmt.Sprintf("%v", [3]float64(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec3d) ToSlice() []float64 { s := make([]float64, 3); copy(s, v[:]); return s }

// ToVec3f converts the components to float32.
func (v Vec3d) ToVec3f() Vec3f {
	var r Vec3f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// Vec4d is a fixed-length vector of 4 float64 values, mirroring
// OpenCV's cv::Vec4d. Elements are stored in index order.
type Vec4d [4]float64

// NewVec4d builds a Vec4d from its 4 components.
func NewVec4d(x float64, y float64, z float64, w float64) Vec4d {
	return Vec4d{x, y, z, w}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec4d) At(i int) float64 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float64 arithmetic wraps).
func (v Vec4d) Add(o Vec4d) Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec4d) Sub(o Vec4d) Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec4d) Mul(s float64) Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec4d) MulElem(o Vec4d) Vec4d {
	var r Vec4d
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec4d) Dot(o Vec4d) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec4d) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec4d) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec4d) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec4d) Equals(o Vec4d) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec4d) Normalize() Vec4d {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec4d
	for i := range v {
		r[i] = float64(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec4d) String() string { return fmt.Sprintf("%v", [4]float64(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec4d) ToSlice() []float64 { s := make([]float64, 4); copy(s, v[:]); return s }

// ToVec4f converts the components to float32.
func (v Vec4d) ToVec4f() Vec4f {
	var r Vec4f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}

// Vec6d is a fixed-length vector of 6 float64 values, mirroring
// OpenCV's cv::Vec6d. Elements are stored in index order.
type Vec6d [6]float64

// NewVec6d builds a Vec6d from its 6 components.
func NewVec6d(x float64, y float64, z float64, w float64, a float64, b float64) Vec6d {
	return Vec6d{x, y, z, w, a, b}
}

// At returns element i of the vector. It panics if i is out of range.
func (v Vec6d) At(i int) float64 { return v[i] }

// Add returns the element-wise sum v+o (no saturation; float64 arithmetic wraps).
func (v Vec6d) Add(o Vec6d) Vec6d {
	var r Vec6d
	for i := range v {
		r[i] = v[i] + o[i]
	}
	return r
}

// Sub returns the element-wise difference v-o.
func (v Vec6d) Sub(o Vec6d) Vec6d {
	var r Vec6d
	for i := range v {
		r[i] = v[i] - o[i]
	}
	return r
}

// Mul returns the vector scaled by s.
func (v Vec6d) Mul(s float64) Vec6d {
	var r Vec6d
	for i := range v {
		r[i] = v[i] * s
	}
	return r
}

// MulElem returns the element-wise (Hadamard) product v*o.
func (v Vec6d) MulElem(o Vec6d) Vec6d {
	var r Vec6d
	for i := range v {
		r[i] = v[i] * o[i]
	}
	return r
}

// Dot returns the dot product of v and o accumulated in float64.
func (v Vec6d) Dot(o Vec6d) float64 {
	var s float64
	for i := range v {
		s += float64(v[i]) * float64(o[i])
	}
	return s
}

// NormSq returns the squared L2 norm (v dot v) in float64.
func (v Vec6d) NormSq() float64 { return v.Dot(v) }

// Norm returns the Euclidean (L2) length of the vector.
func (v Vec6d) Norm() float64 { return math.Sqrt(v.Dot(v)) }

// NormL1 returns the L1 (Manhattan) norm as a float64.
func (v Vec6d) NormL1() float64 {
	var s float64
	for i := range v {
		s += math.Abs(float64(v[i]))
	}
	return s
}

// Equals reports whether v and o have identical components.
func (v Vec6d) Equals(o Vec6d) bool {
	for i := range v {
		if v[i] != o[i] {
			return false
		}
	}
	return true
}

// Normalize returns the unit vector in the direction of v. A zero
// vector is returned unchanged.
func (v Vec6d) Normalize() Vec6d {
	n := v.Norm()
	if n == 0 {
		return v
	}
	var r Vec6d
	for i := range v {
		r[i] = float64(float64(v[i]) / n)
	}
	return r
}

// String renders the vector as [a, b, ...].
func (v Vec6d) String() string { return fmt.Sprintf("%v", [6]float64(v)) }

// ToSlice returns the components as a freshly allocated slice.
func (v Vec6d) ToSlice() []float64 { s := make([]float64, 6); copy(s, v[:]); return s }

// ToVec6f converts the components to float32.
func (v Vec6d) ToVec6f() Vec6f {
	var r Vec6f
	for i := range v {
		r[i] = float32(v[i])
	}
	return r
}
